version: '3.5'


services:
  etcd: 
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - greeter
    
  greeter-srv:
    image: greeter-service:latest
    ports:
      - 50051:50051
    networks:
      - greeter
    depends_on:
      - etcd

  greeter-cli:
    image: greeter-client:latest
    ports:
      - 3000:3000
    networks:
      - greeter
    depends_on:
      - etcd
   

networks:
  greeter:
    driver: bridge